--  Get the total revenue generated by the specific partnership for a company

SELECT 
    pc.company_id,
    c.company_name,
    p.id AS partnership_id,
    p.partnership_name,
    SUM(o.amount) AS total_revenue
FROM 
    Opportunities o
JOIN 
    Leads l ON o.lead_id = l.id
JOIN 
    Campaign cam ON l.campaign_id = cam.id
JOIN 
    Partnership p ON cam.partnership_id = p.id
JOIN 
    Partner_Company pc ON pc.partnership_id = p.id
JOIN 
    Company c ON pc.company_id = c.id
WHERE 
    p.id = 1
    AND pc.invite_accepted = TRUE
GROUP BY 
    pc.company_id, c.company_name, p.id, p.partnership_name;
